export const strings = {
    name: "Name",
    contact_info: "Contact info",
    diagnosis_status: "Diagnosis status",
    actions: "Actions",
    delete: "Delete",
    edit: "Edit",
    update: "Update",
    create: "Create",
    create_new_patient: "Create a new patient",
    enter_valid_email: "Enter valid email",
    enter_email: "Enter email",
    enter_name: "Enter full name",
    enter_date_of_birth: "Enter date of birth",
    enter_phone: "Enter phone",
}